version: '3'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - postgresql_db:/var/lib/postgresql/data/
    networks:
      app:

  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    container_name: django_web
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    #volumes:
      #- ./:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      app:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/app/staticfiles:/www/static
      - ./src/app/media:/www/media
    depends_on:
      - web
    networks:
      app:

volumes:
  postgresql_db:

networks:
  app: